# Generated by Django 5.0.1 on 2024-01-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=155)),
                ('contact_number', models.CharField(max_length=100)),
                ('mc_dot_number', models.CharField(max_length=155)),
                ('number_or_trucks', models.CharField(max_length=100)),
                ('fuel_cards_register', models.CharField(max_length=100)),
                ('mailing_address', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('primary_contact_info', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(default=0)),
                ('email_address', models.EmailField(max_length=170)),
                ('signage', models.CharField(max_length=200)),
            ],
        ),
    ]
