# Generated by Django 5.0.1 on 2024-01-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='file',
            field=models.FileField(default='/home/kenzhegulov/Downloads/eders.text', upload_to=''),
        ),
    ]
