# Generated by Django 5.0.1 on 2024-01-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_card_file_alter_card_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='primary_contact_info',
            field=models.CharField(max_length=100),
        ),
    ]
