# Generated by Django 5.0.1 on 2024-01-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_alter_card_signage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='signage',
            field=models.ImageField(upload_to='signage/'),
        ),
    ]
